version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: student_grading_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_grading_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/schema.sql
    volumes:
      - mysql_grading_system_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_grading_system_data:
