version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: university_mysql_v3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_grading_system_v3_data:/var/lib/mysql

volumes:
  mysql_grading_system_v3_data:
